//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityClean3.Resources.General {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Crud {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Crud() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecurityClean3.Resources.General.Crud", typeof(Crud).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка доступа.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Администратор.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь.
        /// </summary>
        public static string ApplicationUser {
            get {
                return ResourceManager.GetString("ApplicationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад к списку.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор полномочий.
        /// </summary>
        public static string ChooseRole {
            get {
                return ResourceManager.GetString("ChooseRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление документа.
        /// </summary>
        public static string ClearDocLink {
            get {
                return ResourceManager.GetString("ClearDocLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Договор.
        /// </summary>
        public static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приложение: Объект.
        /// </summary>
        public static string ContractSecuredItem {
            get {
                return ResourceManager.GetString("ContractSecuredItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приложение: Услуга.
        /// </summary>
        public static string ContractService {
            get {
                return ResourceManager.GetString("ContractService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание документа.
        /// </summary>
        public static string CreateDocLink {
            get {
                return ResourceManager.GetString("CreateDocLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать запись.
        /// </summary>
        public static string CreateLink {
            get {
                return ResourceManager.GetString("CreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание записи.
        /// </summary>
        public static string CreateTitle {
            get {
                return ResourceManager.GetString("CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказчик.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string DeleteLink {
            get {
                return ResourceManager.GetString("DeleteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление записи.
        /// </summary>
        public static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подробнее.
        /// </summary>
        public static string DetailsLink {
            get {
                return ResourceManager.GetString("DetailsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подробная информация.
        /// </summary>
        public static string DetailsTitle {
            get {
                return ResourceManager.GetString("DetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание документа.
        /// </summary>
        public static string DocCreateTitle {
            get {
                return ResourceManager.GetString("DocCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание! После создания документа, последующее редактирование договора будет невозможно..
        /// </summary>
        public static string DocCreateWarning {
            get {
                return ResourceManager.GetString("DocCreateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить документ.
        /// </summary>
        public static string DownloadLink {
            get {
                return ResourceManager.GetString("DownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать.
        /// </summary>
        public static string EditLink {
            get {
                return ResourceManager.GetString("EditLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование записи.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сотрудник.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сотрудники.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список записей.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Договоров.
        /// </summary>
        public static string ListContract {
            get {
                return ResourceManager.GetString("ListContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приложений: Услуг.
        /// </summary>
        public static string ListCS {
            get {
                return ResourceManager.GetString("ListCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приложений: Объект.
        /// </summary>
        public static string ListCSI {
            get {
                return ResourceManager.GetString("ListCSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказчиков.
        /// </summary>
        public static string ListCustomer {
            get {
                return ResourceManager.GetString("ListCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сотрудников.
        /// </summary>
        public static string ListEmployee {
            get {
                return ResourceManager.GetString("ListEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Должностей.
        /// </summary>
        public static string ListPosition {
            get {
                return ResourceManager.GetString("ListPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Услуг.
        /// </summary>
        public static string ListService {
            get {
                return ResourceManager.GetString("ListService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объектов.
        /// </summary>
        public static string ListSI {
            get {
                return ResourceManager.GetString("ListSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователей.
        /// </summary>
        public static string ListUser {
            get {
                return ResourceManager.GetString("ListUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заблокировано(записано в doc).
        /// </summary>
        public static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Менеджер.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вперед.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смена пароля.
        /// </summary>
        public static string PasswordLink {
            get {
                return ResourceManager.GetString("PasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смена пароля.
        /// </summary>
        public static string PasswordTitle {
            get {
                return ResourceManager.GetString("PasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Должность.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смена полномочий.
        /// </summary>
        public static string RoleLink {
            get {
                return ResourceManager.GetString("RoleLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полномочия.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смена полномочий.
        /// </summary>
        public static string RoleTitle {
            get {
                return ResourceManager.GetString("RoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск(ФИО/Email) :.
        /// </summary>
        public static string SearchAppUser {
            get {
                return ResourceManager.GetString("SearchAppUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        public static string SearchBtn {
            get {
                return ResourceManager.GetString("SearchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск(Номер) :.
        /// </summary>
        public static string SearchContract {
            get {
                return ResourceManager.GetString("SearchContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск(Номер договора или адрес) :.
        /// </summary>
        public static string SearchContractSecuredItem {
            get {
                return ResourceManager.GetString("SearchContractSecuredItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск(Номер договора или наименование) :.
        /// </summary>
        public static string SearchContractService {
            get {
                return ResourceManager.GetString("SearchContractService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск(Название/Адрес/Представитель) :.
        /// </summary>
        public static string SearchCustomer {
            get {
                return ResourceManager.GetString("SearchCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск(ФИО или должность) :.
        /// </summary>
        public static string SearchEmployee {
            get {
                return ResourceManager.GetString("SearchEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск(название или оклад) :.
        /// </summary>
        public static string SearchPosition {
            get {
                return ResourceManager.GetString("SearchPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск(название или адрес) :.
        /// </summary>
        public static string SearchSecuredItem {
            get {
                return ResourceManager.GetString("SearchSecuredItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск(наименование или стоимость) :.
        /// </summary>
        public static string SearchService {
            get {
                return ResourceManager.GetString("SearchService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объект.
        /// </summary>
        public static string SecuredItem {
            get {
                return ResourceManager.GetString("SecuredItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объекты.
        /// </summary>
        public static string SecuredItems {
            get {
                return ResourceManager.GetString("SecuredItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Услуга.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Услуги.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить запись?.
        /// </summary>
        public static string SureDelete {
            get {
                return ResourceManager.GetString("SureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Незаблокировано(не записано в doc).
        /// </summary>
        public static string Unlocked {
            get {
                return ResourceManager.GetString("Unlocked", resourceCulture);
            }
        }
    }
}
